### ISSUE TITLE
Preview for the "Add Note"

### ISSUE THREAD

**Issue by ajtruckle** [mludlum/MarkdownPreview#2]
I can now start a new issue, and for all edit boxes when I click into another edit box it shows a preview:

![snap1](https://user-images.githubusercontent.com/7985331/27639669-cfcd5d3e-5c0e-11e7-82e5-7885a348f2b7.png)

But when I go to **add a note** on an existing issue:

![snap2](https://user-images.githubusercontent.com/7985331/27639687-df9e072c-5c0e-11e7-83ca-35690a8eee88.png)

I have no joy. I can't work out how to get the preview to display.

This is why a timer or button would be handy.

**Comment by mludlum** [comment]
I just committed a fix to work on other pages.  I was limiting my search to the create and update pages. I don't have time to implement the button feature yet.  I think a full WYSIWYG editor would be better.

**Comment by ajtruckle** [comment]
Thank you. So if I download the latest ZIP again and put it on the website it should be OK?

**Comment by mludlum** [comment]
yes

**Comment by ajtruckle** [comment]
Hhm. Doesn't seem to work.

**Comment by mludlum** [comment]
can you give me a url where I can see it not working?

**Comment by ajtruckle** [comment]
Please temporarily sign up at www.publictalksoftware.co.uk/mantisbt<http://www.publictalksoftware.co.uk/mantisbt> and we can try

Sent from my iPhone

On 28 Jun 2017, at 16:21, mludlum <notifications@github.com<mailto:notifications@github.com>> wrote:


can you give me a url where I can see it not working?

**Comment by mludlum** [comment]
sorry about that.  I made a bad edit.  Please try again.

**Comment by ajtruckle** [comment]
Will check later. Back home soon. I noticed a iPhone also doesn't work when swapping text boxes.

Sent from my iPhone

On 28 Jun 2017, at 16:54, mludlum <notifications@github.com<mailto:notifications@github.com>> wrote:


sorry about that. I made a bad edit. Please try again.

**Comment by ajtruckle** [comment]
Seems better. See my reply in MantisBT issue. Thanks.

**Comment by mludlum** [comment]
I agree there are usability issues.  Will think about this.  I'm strapped for time right now.

**Comment by mludlum** [comment]
Just tested on iPhone 5s.  Preview appears when going from one text area to another.
