### ISSUE TITLE
Are any changes needed for this to work with Mantis BT 2.7.0

### ISSUE THREAD

**Issue by ajtruckle** [mludlum/MarkdownPreview#3]
Thanks

**Comment by mludlum** [comment]
I don't know.  You'll have to try it.

**Comment by ajtruckle** [comment]
I am not sure which plugin this refers to but when I click the **Preview** button I notice this:

![mantis](https://user-images.githubusercontent.com/7985331/31860245-42609b9e-b70f-11e7-971c-d5a74db5a769.jpg)

I have no such folder. Nor did version 2.5.1.

**Comment by ajtruckle** [comment]
Please see:

http://mantisbt.org/forums/viewtopic.php?f=2&t=25057

**Comment by ajtruckle** [comment]
Ah, I see, the folder is different ....

vendor\erusev\parsedown

instead of

vendor\parsedown

So what needs changing?

**Comment by ajtruckle** [comment]
I created a fork. That stops the error.

But I can't actually remember how this plugin is support to operate. The error stops but can I kindly ask you further check to see if there is any other behaviour changes from before?

Thank you.

**Comment by ajtruckle** [comment]
Are you able to implement this please?

I would also like your help on my MantisBt because I have got myself confused about two of my plugins. Yours is one of them. And I am not sure what is going on.

**Comment by mludlum** [comment]
I updated mpconvert.php to fix this issue.  I tested the change on v2.7 and it works.

**Comment by ajtruckle** [comment]
Thanks.
