### ISSUE TITLE
Preview and bullets

### ISSUE THREAD

**Issue by ajtruckle** [mludlum/MarkdownPreview#4]
If we now do lists with:

* text
- text
1. text

They show right in the final text. But not in the preview. It shows as a bullet for all of them.

**Comment by mludlum** [comment]
Make sure there is a carriage return between the bullets and the numbered lists.
* bullet 1
* bullet 2

1.  number 1
2.  number 2

**Comment by ajtruckle** [comment]
This is my text:

```
* One
* Two

1. One
2. Two
```

Before preview:
![beforepreview](https://user-images.githubusercontent.com/7985331/32112412-28da73be-bb35-11e7-82a2-58415342d2bb.png)

Clicking preview:
![clickpreview](https://user-images.githubusercontent.com/7985331/32112456-3fbb240c-bb35-11e7-9e38-6fed6bb4a3d5.png)

As you can see I am confused.

**Comment by ajtruckle** [comment]
Ah it is ok. I had to re-enable your plug in.

Thanks.
