### ISSUE TITLE
Using images

### ISSUE THREAD

**Issue by ajtruckle** [mludlum/MarkdownPreview#5]
I am not sure how to handle this and where the bug lies with.

When we insert images we have three components:

The first component is alternative text.
The second component is the url.
The third component is the tooltip.

Now, when I use the preview toolbar it creates the markdown correctly. And I edit the two extra text objects. 

And, the preview below shows correctly with the image and the tooltip. But you try clicking Add Note. The image does not show right.

The only way to get the image to show right is the remove the third component with the tooltip text. Then it shows. So is this a MantisBT bug?

**Comment by ajtruckle** [comment]
Thoughts?

**Comment by mludlum** [comment]
Give me example markdown markup for this with an absolute URL for the image.

**Comment by ajtruckle** [comment]
Please watch this video:

https://www.dropbox.com/s/7efrpsyyecb9lm2/Images-MantisBT.mp4?dl=0

I can't give you a direct URL as mantisBT needs you to have the images on your server. I wish it allowed to upload images like on stackoverflow. :(

**Comment by mludlum** [comment]
I don't need a video.  I need the text you're typing into the text field which fails.  Can you post that please?

**Comment by ajtruckle** [comment]
It is easy to repeat. Insert an image with the button. And you end up with:

`![Description 1](http://www.publictalksoftware.co.uk/screenshots/AddTalk.png "Tip Text")`

That will preview fine but when inserted into MantisBT it will not display.

For it to display you have to remove the tip text:

`![Description 1](http://www.publictalksoftware.co.uk/screenshots/AddTalk.png)`

**Comment by mludlum** [comment]
this works for me
`![Description 1](images/mantis_logo.png "Tip Text")
`
Right-click on your web page and choose Inspect.  Look at the console.  You may have cross-site errors that you cannot avoid.  Try using https instead of http if you're connected over https.   

If you're putting images on the server, put them under your installation folder.  If you use the Add File feature, then you need to get the url of that image AFTER you submit and view it.  The url will be something like this:

**file_download.php?file_id=3&type=bug&show_inline=1&file_show_inline_token=201801089hVQbx8B5SZ7gIeQ9cvd_Gkx90TNhsa_**

**Comment by ajtruckle** [comment]
The issue is not the path to the image. You must have them on your domain or mantisbt. That si not the problem.


The problem is the syntax of "tip text". Did you try it?


![description] (path to image, "tip text")


It is teh "tip text" part in the line. If it is present then mantis will not show the image.


________________________________

**Comment by ajtruckle** [comment]
I have removed the video now but if you had watched it you might have understood better what is happening at my end. I don't consider this a issue with your code or the preview plugin. I actually consider this to be a mantis issue.


________________________________

**Comment by mludlum** [comment]
Did you copy my example and try it?  It shows the mantis logo and if you hover over it, you will see "tip text".  If you have a bad URL, you'll see "Description 1" which is the alternate text when the image cannot be displayed.

**Comment by ajtruckle** [comment]
![edit1](https://user-images.githubusercontent.com/7985331/34693298-f154e93c-f4ba-11e7-8cbd-bc64295115b4.jpg)

![edit2](https://user-images.githubusercontent.com/7985331/34693300-f1731222-f4ba-11e7-91d4-ce6afb2a1888.jpg)

![edit3](https://user-images.githubusercontent.com/7985331/34693301-f195c70e-f4ba-11e7-8d20-8f52c3d5b53a.jpg)

![edit4](https://user-images.githubusercontent.com/7985331/34693302-f1b1722e-f4ba-11e7-9210-1d132d2edbf0.jpg)

![edit5](https://user-images.githubusercontent.com/7985331/34693297-f1345190-f4ba-11e7-9583-20d2caa6dc5e.jpg)

Look above. I did try to show you in the video.  Paths are not the issue. We are talking about MantisBT parsing the image markdown correctly. Whilst the preview toolbar etc does it OK the final topic doesn't. It becomes clear from my images attached. You shoudl be able to follow my instructiosn and replicate yourself.

**Comment by mludlum** [comment]
Yes, it could be an issue with the MantisCoreFormatting plugin.  Use single quotes as a workaround.

`![Description 1](track/images/mantis_logo.png 'test title')
`
