### ISSUE TITLE
Another error

### ISSUE THREAD

**Issue by ajtruckle** [mludlum/MarkdownPreview#7]
I get this error after upgrading to 2.10.0:

![error](https://user-images.githubusercontent.com/7985331/34654894-b81dc362-f3f9-11e7-91b3-f770637c2a09.jpg)

As soon as I click the preview button.

The code seems correct in your plugin so I am confused.

**Comment by mludlum** [comment]
Here is a fix for you:
https://github.com/mludlum/MarkdownPreview/commit/fdba1b5fdfffe8723ecb2b1979085dbb49f6c296
