### ISSUE TITLE
Trying to use strikeout markdown with MantisBT

### ISSUE THREAD

**Issue by ajtruckle** [mludlum/MarkdownPreview#8]
So, I have this code for my note:

```
If we do implement this the list of assignments is now simpler I think:

* Prayer Open
* Prayer Close
* Chairman
* Auxiliary Classroom Counsellor
* Treasure from God Word 1 / 2
* <del>Apply Yourself to Ministry Presentations</del>
* Living as Christian 1 / 2
* CBS Conductor / reader

We would no longer need a Presentations item to be highlighted.

But we do have some questions. Would any of the names for the aforementioned assignments also get highlighted for:

- Student items
- Weekend items

Make sense?
```
When I preview it the note looks fine:

![preview](https://user-images.githubusercontent.com/7985331/37725814-b9270d66-2d2b-11e8-96a9-3152359555d7.jpg)

See that the strikeout text is correctly shown?

But when I add the note it ends up like this:

![note](https://user-images.githubusercontent.com/7985331/37725944-0f260d52-2d2c-11e8-90c1-e2e9df1f750a.jpg)

Why is this?

**Comment by libregeek** [comment]
It might be a MantisBT-ParseDown implementation issue.

**Comment by atrol** [comment]
I assume this is the root cause https://www.mantisbt.org/bugs/view.php?id=24241

Independent from that I would use Markdown syntax instead of HTML del tag to strikethrough text.
`~~Scratch this.~~`
~~Scratch this.~~

**Comment by mludlum** [comment]
ajtruckle, please close this issue if atrol's suggestion works.

**Comment by ajtruckle** [comment]
Thank you for that @atrol
