### ISSUE TITLE
"error" popup when leaving site

### ISSUE THREAD

**Issue by sagamusix** [mludlum/MarkdownPreview#9]
For example when pressing the submit button for an issue, you can briefly see an error message popping up. Since failures in this plugin are not critical to the system, I suggest logging them to the Console instead, or not logging them at all in a standard setup.

**Comment by ajtruckle** [comment]
This was discussed [here](https://github.com/mludlum/MarkdownPreview/issues/6) and he mentions the code to comment out. This will stop the auto-preview though.

**Comment by sagamusix** [comment]
There is no need to remove all of it. Just the useless alert() needs to 
be commented out to get rid of the error message. There's no reason for 
it to be active in production code.

**Comment by mludlum** [comment]
sorry for the delay.  I replaced the alert with console.log

**Comment by sagamusix** [comment]
Thanks!

**Comment by ajtruckle** [comment]
I replaced my file with the new one. Is it supposed to still auto refresh?

**Comment by mludlum** [comment]
auto refresh?  I don't understand your question.

**Comment by ajtruckle** [comment]
The whole point of the **timer** was to **update the preview** as you type. With the preview **showing below**. Now we don't see a preview anymore unless we hit the preview button on the editor toolbar.

**Comment by mludlum** [comment]
Do you have a test site I can look at?

**Comment by ajtruckle** [comment]
Https://www.publictalksoftware.co.uk/mantisbt

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by mludlum** [comment]
Using Chrome, right-click on your page, choose Inspect, and then look at the Console to see the real issue.  
Your server or mantis is returning the wrong content-type for mpreview.php.  I don't know why.  I installed 2.15 and did not get the problem.  You have 2.14.  You could try installing the new version to see if that fixes it.   In mpreview.php, I'm explicitly setting the content type.  On my server, if I changed the content-type, it worked, so I know line 2 of mpreview.php is working .

**Comment by ajtruckle** [comment]
Sorted. I downloaded your complete module, unzipped and uploaded. All working. :)
